interface RuntimeConf {
  umamiWebsiteId?: string | null;
  umamiSrc?: string | null;
  umamiDomains?: string | null;
  gaGameKey?: string | null;
  gaSecretKey?: string | null;
}

declare global {
  interface Window {
    __OE_CONF?: RuntimeConf;
    umami?: { track: (name: string, data?: Record<string, unknown>) => void };
  }
}

// Runtime config (GET /config.js, generated by the game server from its env)
// wins over build-time Vite vars: keys are set in the hosting panel and apply
// on the next launch, no client rebuild needed. The VITE_ path stays as a
// fallback for local dev via client/.env. No real ids or domains live in the
// repo — everything identifying comes from env.
const conf: RuntimeConf = window.__OE_CONF ?? {};
const env = import.meta.env;
const UMAMI_ID = conf.umamiWebsiteId || env.VITE_UMAMI_WEBSITE_ID;
const UMAMI_SRC = conf.umamiSrc || env.VITE_UMAMI_SRC || 'https://cloud.umami.is/script.js';
// Comma-separated hostnames Umami should record (its data-domains attribute);
// keeps localhost and preview hosts out of the stats.
const UMAMI_DOMAINS = conf.umamiDomains || env.VITE_UMAMI_DOMAINS;
const GA_KEY = conf.gaGameKey || env.VITE_GA_GAME_KEY;
const GA_SECRET = conf.gaSecretKey || env.VITE_GA_SECRET_KEY;

// Set once the SDK chunk loads; the dynamic import keeps ~50 KB of
// GameAnalytics out of the game bundle when no keys are configured.
let ga: (typeof import('gameanalytics'))['default'] | null = null;

/** Boot whichever external analytics are configured at build time.
 *  Umami (open-source, cookie-less) counts visits/uniques/pageviews on its
 *  own; GameAnalytics tracks sessions itself and receives the design events
 *  sent through track(). With neither configured everything is a no-op. */
export function initAnalytics(): void {
  try {
    if (UMAMI_ID) {
      const s = document.createElement('script');
      s.defer = true;
      s.src = UMAMI_SRC;
      s.dataset.websiteId = UMAMI_ID;
      if (UMAMI_DOMAINS) s.dataset.domains = UMAMI_DOMAINS;
      document.head.appendChild(s);
    }
    if (GA_KEY && GA_SECRET) {
      void import('gameanalytics')
        .then((m) => {
          m.default.initialize(GA_KEY, GA_SECRET);
          ga = m.default;
        })
        .catch(() => undefined);
    }
  } catch {
    // Analytics must never break the game.
  }
}

/** Fan one game event out to every configured service. */
export function track(name: string, data?: Record<string, string | number | boolean>): void {
  try {
    window.umami?.track(name, data);
    ga?.addDesignEvent(`game:${name}`);
  } catch {
    // Analytics must never break the game.
  }
}
