import type { Rules } from '@uno/shared';

interface RuntimeConf {
  umamiWebsiteId?: string | null;
  umamiSrc?: string | null;
  umamiDomains?: string | null;
  gaGameKey?: string | null;
  appVersion?: string | null;
}

declare global {
  interface Window {
    __OE_CONF?: RuntimeConf;
    __oeBeforeSend?: (type: string, payload: Record<string, unknown>) => Record<string, unknown>;
    umami?: { track: (name: string, data?: Record<string, unknown>) => void };
  }
}

// Runtime config (GET /config.js, generated by the game server from its env)
// wins over build-time Vite vars: keys are set in the hosting panel and apply
// on the next launch, no client rebuild needed. The VITE_ path stays as a
// fallback for local dev via client/.env. No real ids or domains live in the
// repo — everything identifying comes from env.
const conf: RuntimeConf = window.__OE_CONF ?? {};
const env = import.meta.env;
const UMAMI_ID = conf.umamiWebsiteId || env.VITE_UMAMI_WEBSITE_ID;
const UMAMI_SRC = conf.umamiSrc || env.VITE_UMAMI_SRC || 'https://cloud.umami.is/script.js';
// Comma-separated hostnames Umami should record (its data-domains attribute);
// keeps localhost and preview hosts out of the stats.
const UMAMI_DOMAINS = conf.umamiDomains || env.VITE_UMAMI_DOMAINS;
const GA_KEY = conf.gaGameKey || env.VITE_GA_GAME_KEY;
// The GameAnalytics secret never travels through /config.js anymore: without
// a local VITE_GA_SECRET_KEY (dev-only escape hatch for talking to the
// collector directly) the SDK runs in relay mode via POST /api/ga/*.
const GA_SECRET = env.VITE_GA_SECRET_KEY;
const APP_VERSION = conf.appVersion || env.VITE_APP_VERSION || 'dev';

// Custom-dimension vocabularies must be declared before initialize; GA drops
// values that are not on the declared list. Rule presets are encoded as a
// 4-bit mask over RULE_ORDER ('classic' for all-off): 16 values, under GA's
// 20-per-dimension cap and immune to rule renaming.
const RULE_ORDER = ['stacking', 'forcePlay', 'drawToMatch', 'multiDiscard'] as const;
const RULE_PRESETS = Array.from({ length: 16 }, (_, i) => {
  const bits = i.toString(2).padStart(4, '0');
  return bits === '0000' ? 'classic' : `r${bits}`;
});

/** Low-cardinality encoding of a house-rules combination (see RULE_ORDER). */
export function rulesPreset(rules: Rules): string {
  const bits = RULE_ORDER.map((k) => (rules[k] ? '1' : '0')).join('');
  return bits === '0000' ? 'classic' : `r${bits}`;
}

// Set once the SDK chunk loads; the dynamic import keeps ~50 KB of
// GameAnalytics out of the game bundle when no keys are configured.
type GASdk = (typeof import('gameanalytics'))['default'];
type GaErrorSeverity = Parameters<GASdk['addErrorEvent']>[0];
type GaProgression = Parameters<GASdk['addProgressionEvent']>[0];
let ga: GASdk | null = null;
let gaSeverities: Record<string, GaErrorSeverity> | null = null;
let gaProgressions: Record<string, GaProgression> | null = null;

export type GaSeverity = 'debug' | 'info' | 'warning' | 'error' | 'critical';

// Dimensions may become known (role: after seating; rules: at deal) before
// the lazy GA chunk finishes loading — buffer them and flush after init.
const dims: { role?: string; form?: string; rules?: string } = {};
function applyDims(): void {
  if (!ga) return;
  if (dims.role) ga.setCustomDimension01(dims.role);
  if (dims.form) ga.setCustomDimension02(dims.form);
  if (dims.rules) ga.setCustomDimension03(dims.rules);
}

/** Segment the session for GA cohorts: host/guest and the rules preset.
 *  Form factor is set automatically at init. Safe to call repeatedly. */
export function setAnalyticsDimensions(d: { role?: 'host' | 'guest'; rules?: Rules }): void {
  try {
    if (d.role) dims.role = d.role;
    if (d.rules) dims.rules = rulesPreset(d.rules);
    applyDims();
  } catch {
    // Analytics must never break the game.
  }
}

/** Boot whichever external analytics are configured at build time.
 *  Umami (open-source, cookie-less) counts visits/uniques/pageviews on its
 *  own; GameAnalytics tracks sessions itself and receives the design events
 *  sent through track(). With neither configured everything is a no-op. */
export function initAnalytics(): void {
  try {
    if (UMAMI_ID) {
      // Room codes must not become distinct "pages": normalize /r/CODE before
      // any payload leaves the tracker (Umami 2.18+ data-before-send).
      const roomPath = /\/r\/[A-Za-z0-9-]+/g;
      window.__oeBeforeSend = (_type, payload) => {
        for (const k of ['url', 'referrer'] as const) {
          const v = payload[k];
          if (typeof v === 'string') payload[k] = v.replace(roomPath, '/r/:code');
        }
        return payload;
      };
      const s = document.createElement('script');
      s.defer = true;
      s.src = UMAMI_SRC;
      s.dataset.websiteId = UMAMI_ID;
      if (UMAMI_DOMAINS) s.dataset.domains = UMAMI_DOMAINS;
      s.dataset.beforeSend = '__oeBeforeSend';
      document.head.appendChild(s);
    }
    if (GA_KEY) {
      void import('gameanalytics')
        .then((m) => {
          // Typings put the API on the default export, but at runtime the
          // ESM bundle's default is a bare stub with no statics — the working
          // class sits on m.gameanalytics.GameAnalytics (verified in-browser).
          // The cast bridges that typings/runtime mismatch.
          const ns = (m as unknown as {
            gameanalytics: {
              GameAnalytics: GASdk;
              EGAErrorSeverity: Record<string, GaErrorSeverity>;
              EGAProgressionStatus: Record<string, GaProgression>;
              http: { GAHTTPApi: { instance: { baseUrl: string; remoteConfigsBaseUrl: string } } };
            };
          }).gameanalytics;
          const sdk = ns.GameAnalytics;
          if (!GA_SECRET) {
            // Relay mode: point the SDK's transport at our own origin, where
            // server/src/ga-relay.ts re-signs with the real GA_SECRET_KEY and
            // forwards — adblock-proof, and no secret in any browser. The SDK
            // insists on a 40-char secret at initialize, so it gets a
            // placeholder; the signature it produces is ignored by the relay.
            const api = ns.http.GAHTTPApi.instance;
            api.baseUrl = '/api/ga/v2';
            api.remoteConfigsBaseUrl = '/api/ga/remote_configs/v1';
          }
          // Build + dimension vocabularies must precede initialize.
          sdk.configureBuild(APP_VERSION);
          sdk.configureAvailableCustomDimensions01(['host', 'guest']);
          sdk.configureAvailableCustomDimensions02(['mobile-web', 'desktop-web']);
          sdk.configureAvailableCustomDimensions03(RULE_PRESETS);
          sdk.initialize(GA_KEY, GA_SECRET || '0'.repeat(40));
          ga = sdk;
          gaSeverities = ns.EGAErrorSeverity;
          gaProgressions = ns.EGAProgressionStatus;
          dims.form = window.matchMedia('(pointer: coarse)').matches ? 'mobile-web' : 'desktop-web';
          applyDims();
        })
        .catch((e) => console.warn('[analytics] GameAnalytics SDK failed to load', e));
    }
  } catch {
    // Analytics must never break the game.
  }
}

/** Fan one game event out to every configured service. A numeric `value`
 *  in data also becomes the GameAnalytics design-event value (count/sum/mean
 *  in their dashboards); everything else is Umami-only event data. */
export function track(name: string, data?: Record<string, string | number | boolean>): void {
  try {
    window.umami?.track(name, data);
    if (typeof data?.value === 'number') ga?.addDesignEvent(`game:${name}`, data.value);
    else ga?.addDesignEvent(`game:${name}`);
  } catch {
    // Analytics must never break the game.
  }
}

/** Round progression for the GameAnalytics Progression dashboard: one
 *  progression type only (rounds), per the taxonomy — Start at deal,
 *  Complete for the winner (score = points when known), Fail for the rest.
 *  mode: classic|house, bucket: 2p|3-4p — never codes or exact counts. */
export function trackProgression(
  status: 'Start' | 'Complete' | 'Fail',
  mode: string,
  bucket: string,
  score?: number,
): void {
  try {
    if (!ga || !gaProgressions) return;
    const st = gaProgressions[status];
    if (st === undefined) return;
    if (score === undefined) ga.addProgressionEvent(st, 'round', mode, bucket);
    else ga.addProgressionEvent(st, 'round', mode, bucket, score);
  } catch {
    // Analytics must never break the game.
  }
}

/** Report an error to the GameAnalytics Health dashboard (no-op until the
 *  SDK chunk is initialized). Callers go through reportError() in errors.ts,
 *  which dedupes and rate-limits — never call this in a loop directly. */
export function gaAddError(severity: GaSeverity, message: string): void {
  try {
    if (!ga || !gaSeverities) return;
    const name = severity.charAt(0).toUpperCase() + severity.slice(1);
    const value = gaSeverities[name];
    if (value === undefined) return;
    ga.addErrorEvent(value, message);
  } catch {
    // Analytics must never break the game.
  }
}
